/*イラスト */
//https://flowerillust.com/html/back/back_pattern0058.html


var CONFIG = CONFIG || {};

CONFIG.FONT = "PingFangHK-Light";
CONFIG.DEBUG_FLAG       = 0;
CONFIG.DEBUG_STAGE_NUM  = 4;
CONFIG.BGM_VOLUME       = 1;
CONFIG.SE_VOLUME        = 1;
CONFIG.CARD_SPEND_COST  = 3;

CONFIG.MAP_WIDTH = 1136*1.2;
CONFIG.MAP_HEIGHT = 640 * 1.2;



CONFIG.ENEMY = [
    { 
    },
    { 
        "id"         : 1,
        "name"       : "",
        "description": "",
        "image"      : "res/enemy-001.png",
        "spriteNum"  : 0,
        "isMove"     : true,
        "scale"      : 1,
        "speed"      : 0.2,
        "width"      : 250,
        "height"     : 250,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 10,
        "deadTime"   : 200,
        "next"       : [6],
        "strong"     : [6],
    },
    { 
        "id"         : 2,
        "name"       : "",
        "description": "",
        "image"      : "res/creature-000.png",
        "spriteNum"  : 1,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.2,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 10,
        "deadTime"   : 200,
        "next"       : [7],
        "strong"     : [6],
    },
    { 
        "id"         : 3, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-000.png",
        "spriteNum"  : 2,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.2,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 2,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 10,
        "deadTime"   : 200,
        "next"       : [8],
        "strong"     : [6],
    },
];


CONFIG.CREATURE = [
    { 
    },
    { 
        "id"         : 1,
        "name"       : "",
        "description": "",
        "image"      : "res/creature-000.png",
        "spriteNum"  : 0,
        "isMove"     : false,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 5,
        "deadTime"   : 20,
        "next"       : [6],
        "strong"     : [6],
    },
    { 
        "id"         : 2,
        "name"       : "",
        "description": "",
        "image"      : "res/creature-000.png",
        "spriteNum"  : 1,
        "isMove"     : false,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 5,
        "deadTime"   : 20,
        "next"       : [7],
        "strong"     : [6],
    },
    { 
        "id"         : 3, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-000.png",
        "spriteNum"  : 2,
        "isMove"     : false,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 2,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 5,
        "deadTime"   : 20,
        "next"       : [8],
        "strong"     : [6],
    },
    { 
        "id"         : 4, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-000.png",
        "spriteNum"  : 3,
        "isMove"     : false,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 5,
        "deadTime"   : 20,
        "next"       : [9],
        "strong"     : [6],
    },
    { 
        "id"         : 5,
        "name"       : "",
        "description": "",
        "image"      : "res/creature-000.png",
        "spriteNum"  : 4,
        "isMove"     : false,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 5,
        "deadTime"   : 20,
        "next"       : [10],
        "strong"     : [6],
    },




    { 
        "id"         : 6, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-002.png",
        "spriteNum"  : 0,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 1,
        "evolutionTime" : 10,
        "deadTime"   : 60,
        "next"       : [11],
        "strong"     : [6],
    },
    { 
        "id"         : 7, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-002.png",
        "spriteNum"  : 1,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 2,
        "evolutionTime" : 20,
        "deadTime"   : 60,
        "next"       : [11],
        "strong"     : [6],
    },
    { 
        "id"         : 8,
        "name"       : "",
        "description": "",
        "image"      : "res/creature-002.png",
        "spriteNum"  : 2,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 2,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 10,
        "deadTime"   : 60,
        "next"       : [11],
        "strong"     : [6],
    },
    { 
        "id"         : 9, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-002.png",
        "spriteNum"  : 3,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 10,
        "deadTime"   : 60,
        "next"       : [11],
        "strong"     : [6],
    },
    { 
        "id"         : 10, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-002.png",
        "spriteNum"  : 4,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 10,
        "deadTime"   : 60,
        "next"       : [11],
        "strong"     : [6],
    },




    { 
        "id"         : 11, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-001.png",
        "spriteNum"  : 0,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 1,
        "evolutionTime" : 10,
        "deadTime"   : 200,
        "next"       : [12],
        "strong"     : [6],
    },
    { 
        "id"         : 12, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-001.png",
        "spriteNum"  : 1,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 2,
        "evolutionTime" : 20,
        "deadTime"   : 200,
        "next"       : [13],
        "strong"     : [6],
    },
    { 
        "id"         : 13,
        "name"       : "",
        "description": "",
        "image"      : "res/creature-001.png",
        "spriteNum"  : 2,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 2,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 10,
        "deadTime"   : 200,
        "next"       : [14],
        "strong"     : [6],
    },
    { 
        "id"         : 14, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-001.png",
        "spriteNum"  : 3,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 10,
        "deadTime"   : 200,
        "next"       : [15],
        "strong"     : [6],
    },
    { 
        "id"         : 15, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-001.png",
        "spriteNum"  : 4,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 10,
        "deadTime"   : 20,
        "next"       : [16],
        "strong"     : [6],
    },
    { 
        "id"         : 16, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-001.png",
        "spriteNum"  : 5,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 10,
        "deadTime"   : 20,
        "next"       : [17],
        "strong"     : [6],
    },
    { 
        "id"         : 17, 
        "name"       : "",
        "description": "",
        "image"      : "res/creature-001.png",
        "spriteNum"  : 6,
        "isMove"     : true,
        "scale"      : 0.8,
        "speed"      : 0.5,
        "width"      : 125,
        "height"     : 125,
        "icon_height": 30,
        "creatureType" : 1,
        "evolutionFoodCnt" : 3,
        "evolutionTime" : 10,
        "deadTime"   : 20,
        "next"       : [18],
        "strong"     : [6],
    },
];
